### ISSUE TITLE
能否创办讨论区

### ISSUE THREAD

**Issue by HoiM** [snowkylin/tensorflow-handbook#25]
感谢作者撰写此学习教程，受益匪浅。现在在学习过程中时常会发现一些问题，但又没有场合提问。请问能否创建一个中文讨论区，以供学习者交流？谢谢！

**Comment by snowkylin** [comment]
Hi, you can just post your question here. English is encouraged but not mandatory. Or you can also leave your question in TensorFlow Official WeChat account. I will usually answer some of the questions at the end of the next serial article.
