### ISSUE TITLE
Is the book `Concise TensorFlow 2` available in English?

### ISSUE THREAD

**Issue by AdityaKane2001** [snowkylin/tensorflow-handbook#59]

**Comment by snowkylin** [comment]
Yes, please find the English version in https://tf.wiki/en/
The translation still has large space of improvement. Suggestions are welcomed.

**Comment by AdityaKane2001** [comment]
@snowkylin 
Thanks for the reply!
Just wanted to ask whether there is info on ops and kernels in TensorFlow in this book.

**Comment by snowkylin** [comment]
This book is more like a tutorial for beginners about how to use TensorFlow to write some basic ML programs. If you want information for a specific op or kernel, maybe you can just search in https://www.tensorflow.org/api_docs/python/tf

**Comment by AdityaKane2001** [comment]
Oh, thanks anyways for the reply!
